# Generated by Django 4.2.8 on 2023-12-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
                ('popularity', models.IntegerField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('danceability', models.FloatField(blank=True)),
                ('wordiness', models.FloatField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.playlist')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist_id', 'track_id'), name='playlist_track_id'),
        ),
    ]
