# Generated by Django 4.2.8 on 2023-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(through='music.PlaylistTrack', to='music.track'),
        ),
    ]
